create table if not exists public.guardias (
  id bigint generated by default as identity primary key,
  guard_date date not null,
  station text not null default 'Parque Campanar',
  payload jsonb not null,
  totals jsonb not null default '{}'::jsonb,
  present_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (guard_date, station)
);

alter table public.guardias enable row level security;

drop policy if exists "Lectura compartida de guardias" on public.guardias;
drop policy if exists "Crear guardias compartidas" on public.guardias;
drop policy if exists "Actualizar guardias compartidas" on public.guardias;

create policy "Lectura compartida de guardias"
on public.guardias for select
using (true);

create policy "Crear guardias compartidas"
on public.guardias for insert
with check (true);

create policy "Actualizar guardias compartidas"
on public.guardias for update
using (true)
with check (true);
